using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using IntegrityTables.SourceGeneration.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace IntegrityTables.SourceGeneration;

[Generator]
[SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Symbols should be compared for equality")]
public partial class DatabaseSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "IntegrityTables";
    private const string AttributeName = "GenerateDatabaseAttribute";
    private const string TableAttributeName = "GenerateTableAttribute";
    private const string ServiceAttributeName = "GenerateServiceAttribute";
    private const string SystemAttributeName = "GenerateSystemAttribute";


    private void GenerateDatabaseCode(SourceProductionContext context, Compilation compilation, ISymbol databaseClass, ImmutableArray<INamedTypeSymbol> _tablestructs, ImmutableArray<INamedTypeSymbol> systemClasses)
    {
        var uniqueTableStructs = _tablestructs
            .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
            .ToImmutableArray();
        
        var uniqueSystemClasses = systemClasses
            .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
            .ToImmutableArray();
        var model = ModelBuilder.Build(context, compilation, (INamedTypeSymbol) databaseClass, uniqueTableStructs, uniqueSystemClasses);
        // DbmlBuilder.Build(context, model);
        // MermaidBuilder.Build(context, model);
        RowContainerSourceGenerator.GenerateCode(context, model);
        // PersistenceSourceGenerator.GenerateCode(context, model);
        SystemSourceGenerator.GenerateCode(context, model);
        
        var sb = new StringBuilder();


        // Generate database class
        sb.AppendLine(@$"// <auto-generated/> {DatabaseSourceGenerator.GenerationStamp()}
using System;
using System.Collections.Generic;
using IntegrityTables;
{GenerateUsings(model)}
");
        if (!string.IsNullOrEmpty(model.NameSpace))
        {
            sb.AppendLine($"namespace {model.NameSpace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($@"
    // {DatabaseSourceGenerator.GenerationStamp()}
    public partial class {model.DatabaseSymbol.Name} : IDatabase
    {{
        public IPersistence Persistence {{ get; set; }}

#region Tables
    // {DatabaseSourceGenerator.GenerationStamp()}
{BuildTableProperties(model)}
#endregion
       
        private ITable[] _tables;
        public ITable[] Tables => _tables;
        // {DatabaseSourceGenerator.GenerationStamp()}
        public void Save()
        {{
            if (Persistence == null)
                throw new InvalidOperationException(""No persistence layer set. Set the Persistence property before calling Save()."");
{GenerateSaveTableCalls(model)}            
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        public void Load()
        {{
            if (Persistence == null)
                throw new InvalidOperationException(""No persistence layer set. Set the Persistence property before calling Load()."");
{GenerateLoadTableCalls(model)}            
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        public {model.DatabaseSymbol.Name}()
        {{
            InitializeTables();
{BuildDefaultDataAndOnLoadTablesMethodCalls(model)}
        }}

#region initialization
        // {DatabaseSourceGenerator.GenerationStamp()}
        private void InitializeTables() {{
{BuildInitializeTables(model)}

            _tables = new ITable[] {{ {string.Join(", ", model.Tables.Select(i => i.FacadeName))} }};
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        private void InitializeUniqueIndexes() {{
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        private void InitializeTriggers() {{
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        private void InitializeConstraints() {{
        }}
#endregion

#region validation
        // {DatabaseSourceGenerator.GenerationStamp()}
        /// <summary>
        /// Confirm that the data in all tables obeys the rules specified in the schema.
        /// </summary>
        public void ValidateIntegrity() {{
{GenerateValidatorMethod(model)}
        }}
#endregion    

        public struct Enumerator : IEnumerator<ITable>
        {{
            private readonly ITable[] _tables;
            private int _index;

            public Enumerator(ITable[] tables)
            {{
                _tables = tables;
                _index = -1;
            }}

            public ITable Current => _tables[_index];

            object System.Collections.IEnumerator.Current => Current;

            public bool MoveNext()
            {{
                _index++;
                return _index < _tables.Length;
            }}

            public void Reset()
            {{
                _index = -1;
            }}

            public void Dispose() {{ }}
        }}

        public Enumerator GetEnumerator()
        {{
            return new Enumerator(_tables);
        }}
    }}

");
        if (!string.IsNullOrEmpty(model.NameSpace)) sb.AppendLine("}");

        context.AddSource($"{model.FileName("Database", "")}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));

        // This outputs different partial class files.
        // BuildReferentialIntegrityMethods(context, model);
    }

    public static string GenerationStamp([CallerFilePath] string filePath = "", [CallerLineNumber] int lineNumber = 0)
    {
        var filename = System.IO.Path.GetFileName(filePath);
        return $"{filename}:{lineNumber}";
    }
    
    private string GenerateLoadTableCalls(DatabaseModel model)
    {
        var sb = new StringBuilder();
        foreach (var table in model.Tables)
        {
            sb.AppendLine($@"            //Persistence.LoadTable<{table.QualifiedTypeName}>(this.{table.FieldName});");
        }

        return sb.ToString();
    }

    private string GenerateSaveTableCalls(DatabaseModel model)
    {
        var sb = new StringBuilder();
        foreach (var table in model.Tables)
        {
            sb.AppendLine($@"            //Persistence.SaveTable<{table.QualifiedTypeName}>(this.{table.FieldName});");
        }

        return sb.ToString();
    }

    private string GenerateUsings(DatabaseModel model)
    {
        var sb = new StringBuilder();
        foreach (var table in model.Tables)
        {
            if (model.NameSpace != table.NameSpace)
                sb.AppendLine($"using {table.NameSpace};");
        }

        return sb.ToString();
    }

    private string BuildDefaultDataAndOnLoadTablesMethodCalls(DatabaseModel model)
    {
        var sb = new StringBuilder();
        foreach (var table in model.Tables)
        {
            if (table.DefaultDataMethods.Count > 0)
                sb.AppendLine($@"            foreach(var row in {table.FieldName}.GetDefaultData()) {table.FacadeName}.Add(row);");
            if (table.GenerateEnum != null)
            {
                sb.AppendLine($@"            foreach(var i in Enum.GetValues(typeof({table.GenerateEnum.Name})))
                {{
                    var row = new Row<{table.QualifiedTypeName}>() {{ id = (int)i }};
                    row.data.name = i.ToString();");
                foreach (var method in table.ConfigureEnumMethods)
                {
                    sb.AppendLine($"                {table.QualifiedTypeName}.{method}(ref row);");
                }
                sb.AppendLine($@"
                    {table.FacadeName}.Add(ref row);
                }}");
            }
        }

        foreach (var m in model.OnTablesCreatedMethods)
        {
            sb.AppendLine($@"            {m}();");
        }

        return sb.ToString();
    }

    private string GenerateClearMethod(DatabaseModel model)
    {
        var sb = new StringBuilder();
        foreach (var table in model.Tables)
        {
            sb.AppendLine(@$"               case var _ when type == typeof({table.QualifiedTypeName}): 
                for(var i = {table.FieldName}.Count -1; i >= 0; i--)
                    {table.FacadeName}.Remove({table.FieldName}[i], cascade);
                break;");
        }

        return sb.ToString();
    }

    private string BuildInitializeTables(DatabaseModel model)
    {
        return string.Join("\n", model.Tables.Select(BuildInitializeTable));

        string BuildInitializeTable(TableModel table)
        {
            return $"            this.{table.FacadeName} = new {table.TypeName}Table(this);";
        }
    }

    private string BuildTableProperties(DatabaseModel model)
    {
        return string.Join("\n", model.Tables.Select(t => $"        public {t.TypeName}Table {t.FacadeName} {{ get; private set; }}"));
    }

    private string GenerateValidatorMethod(DatabaseModel model)
    {
        var sb = new StringBuilder();
        foreach (var table in model.Tables)
        {
            var tableName = table.FieldName;
            var fieldChecks = new StringBuilder();
            var addCheck = false;
            foreach (var field in table.Fields)
            {
                if (!field.IsReference) continue;
                addCheck = true;
                var referencedTableModel = field.ReferencedTableModel;
                var errorMessage = $"{tableName}.{field.FieldSymbol.Name} ({{row.{field.FieldSymbol.Name}}}) is not a valid reference to {referencedTableModel.QualifiedTypeName}";
                if(field.IsNotNull)
                    fieldChecks.AppendLine($@"                if(!{referencedTableModel.FacadeName}.ContainsKey(row.{field.FieldSymbol.Name})) Warnings.Warn($""{errorMessage}"");");
                else
                    fieldChecks.AppendLine($@"                if(row.{field.FieldSymbol.Name} >= 0 && !{referencedTableModel.FacadeName}.ContainsKey(row.{field.FieldSymbol.Name})) Warnings.Warn($""{errorMessage}"");");
            }

            if (addCheck)
                sb.AppendLine($@"            foreach (var id in this.{table.FacadeName}) 
            {{
                var row = this.{table.FacadeName}.Get(id);
{fieldChecks}                    
            }}");
        }

        return sb.ToString();
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get all structs with [GenerateTable] attribute
        var tableStructsProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is StructDeclarationSyntax,
                (ctx, _) => GetStructWithTableAttribute(ctx))
            .Where(t => t.hasTableAttribute)
            .Select((t, _) => (INamedTypeSymbol) t.symbol)
            .Collect();

        var systemClassesProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) =>
                {
                    return GetClassWithSystemAttribute(ctx);
                })
            .Where(t => t.hasSystemAttribute)
            .Select((t, _) => (INamedTypeSymbol) t.symbol)
            .Collect();

        // Get all classes with [GenerateDatabase] attribute
        var databaseClassesProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) => GetClassWithDatabaseAttribute(ctx))
            .Where(t => t.hasDatabaseAttribute)
            .Select((t, _) => (INamedTypeSymbol) t.symbol);

        //     
        // Generate the source code
        var allInputs = databaseClassesProvider.Combine(tableStructsProvider).Combine(systemClassesProvider).Combine(context.CompilationProvider);
        context.RegisterSourceOutput(allInputs, (ctx, source) =>
        {
            var (((dbClass, tableStructs), systems), compilation) = source;
            GenerateDatabaseCode(ctx, compilation, dbClass, tableStructs, systems);
        });
    }

    private static (ISymbol symbol, bool hasTableAttribute) GetStructWithTableAttribute(GeneratorSyntaxContext context)
    {
        var structDeclaration = (StructDeclarationSyntax) context.Node;
        var semanticModel = context.SemanticModel;
        var structSymbol = semanticModel.GetDeclaredSymbol(structDeclaration);

        if (structSymbol == null)
            return (null, false);

        foreach (var attribute in structSymbol.GetAttributes())
            if (attribute.AttributeClass?.ToDisplayString() == $"{Namespace}.{TableAttributeName}")
                return (structSymbol, true);

        return (structSymbol, false);
    }

    private static (ISymbol symbol, bool hasSystemAttribute) GetClassWithSystemAttribute(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax) context.Node;
        var semanticModel = context.SemanticModel;
        var symbol = semanticModel.GetDeclaredSymbol(declaration);

        if (symbol == null)
            return (null, false);

        foreach (var attribute in symbol.GetAttributes())
            if (attribute.AttributeClass?.ToDisplayString() == $"{Namespace}.{SystemAttributeName}")
                return (symbol, true);

        return (symbol, false);
    }

    private static (ISymbol symbol, bool hasDatabaseAttribute) GetClassWithDatabaseAttribute(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax) context.Node;
        var semanticModel = context.SemanticModel;
        var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

        if (classSymbol == null)
            return (null, false);

        foreach (var attribute in classSymbol.GetAttributes())
            if (attribute.AttributeClass?.ToDisplayString() == $"{Namespace}.{AttributeName}")
                return (classSymbol, true);

        return (classSymbol, false);
    }
}
