using System.Text;
using IntegrityTables.SourceGeneration.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace IntegrityTables.SourceGeneration;

public partial class DatabaseSourceGenerator
{
    private void BuildReferentialIntegrityMethods(SourceProductionContext context, DatabaseModel model)
    {
        foreach (var table in model.Tables)
        {
            var sb = new StringBuilder();
            sb.AppendLine($@"// <auto-generated/> // {DatabaseSourceGenerator.GenerationStamp()}
using System;
using System.Collections.Generic;
using IntegrityTables;
");
            if (!string.IsNullOrEmpty(model.NameSpace))
            {
                sb.AppendLine($"namespace {model.NameSpace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    public partial class {model.DatabaseSymbol.Name} {{");
            sb.AppendLine();
            sb.AppendLine($"        public {table.TypeName}Table {table.TypeName}Table => this.{table.FieldName};");
            var tableTypeName = table.QualifiedTypeName;
            var tableFieldName = table.FieldName;
            sb.AppendLine();
            BuildAddMethod(sb, table);
            sb.AppendLine();
            sb.AppendLine("    }");
            if (!string.IsNullOrEmpty(model.NameSpace))
            {
                sb.AppendLine("}");
            }
            context.AddSource($"{model.FileName("ReferentialIntegrity", table.TypeName)}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static void BuildRemoveMethod(StringBuilder sb, TableModel table)
    {
        var tableFieldName = table.FieldName;

        var tableTypeName = table.QualifiedTypeName;
        sb.AppendLine($@"        // {DatabaseSourceGenerator.GenerationStamp()}
        private void ExecuteCascadingRemove{table.TypeName}Row(int id, CascadeOperation cascade) {{
            var row = this.{tableFieldName}.Get(id);");
        foreach (var dependentField in table.Dependencies)
        {
            var dependentTableFieldName = dependentField.TableModel.FieldName;
            var errorMessage = $"\"{dependentTableFieldName}.{dependentField.Name} contains reference to {table.FieldName}\"";
            sb.AppendLine($@"
            // remove all dependent rows from {dependentTableFieldName}      
            for(var i = {dependentTableFieldName}.Count - 1; i >= 0; i--)
            {{
                var xrow = {dependentTableFieldName}[i];
                if(xrow.{dependentField.Name} != id) continue;
                switch(cascade) 
                {{
                    case CascadeOperation.None:
                        throw new InvalidOperationException({errorMessage});
                        break;
                    case CascadeOperation.Delete:
                        {dependentTableFieldName}.Remove(xrow.id, cascade);
                        break;
                    case CascadeOperation.SetNull:  
{GenerateSetNullBlock(dependentField)}                                          
                }}
            }}");

            string GenerateSetNullBlock(FieldModel fieldModel)
            {
                if (fieldModel.IsNotNull)
                    return $"                        throw new InvalidOperationException(\"{fieldModel.Name} is marked NotNull\");";
                return @$"                        var copy = {fieldModel.TableModel.FacadeName}.Get(xrow.id); 
                        copy.{fieldModel.Name} = 0; 
                        break;";
            }
        }
        sb.AppendLine("        }");
    }

    private static void BuildAddMethod(StringBuilder sb, TableModel table)
    {
        var tableFieldName = table.FieldName;
        var refCheckBuilder = new StringBuilder();
        foreach (var refField in table.Fields)
        {
            if (!refField.IsReference) continue;
            var refTableFieldName = refField.ReferencedTableModel.FieldName;
            var errorMessage = $"{refField.Name} is not a valid reference to {refTableFieldName} ({{row.{refField.Name}}})";
            refCheckBuilder.AppendLine($@"            if(row.{refField.Name} >= 0 && !{refTableFieldName}.ContainsKey(row.{refField.Name})) 
                throw new InvalidOperationException($""{errorMessage}"");");
        }

        sb.AppendLine();
        var tableTypeName = table.QualifiedTypeName;
        sb.AppendLine($@"        // {DatabaseSourceGenerator.GenerationStamp()}
        private void CheckReferentialIntegrityOn{table.TypeName}({tableTypeName}Row row) {{
{refCheckBuilder}
        }}");
    }
}