using System.Collections.Generic;
using System.Linq;
using System.Text;
using IntegrityTables.SourceGeneration.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace IntegrityTables.SourceGeneration;

public class PersistenceSourceGenerator 
{
    public static void GenerateCode(SourceProductionContext context, DatabaseModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine($@"// <auto-generated/> //  {DatabaseSourceGenerator.GenerationStamp()}
{(string.IsNullOrEmpty(model.NameSpace)?"":$"namespace {model.NameSpace};")}        



");
        context.AddSource($"{model.FileName("Persistence", model.DatabaseSymbol.Name)}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));


    }
}