using System.Text;
using IntegrityTables.SourceGeneration.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace IntegrityTables.SourceGeneration;

public class RowContainerSourceGenerator 
{
    public static void GenerateCode(SourceProductionContext context, DatabaseModel model)
    {
        foreach (var table in model.Tables)
        {
            GenerateRowContainer(context, model, table);
            RowFacadeSourceGenerator.GenerateCode(context, model, table);
            TableSourceGenerator.GenerateCode(context, model, table);
        }
    }

    private static void GenerateRowContainer(SourceProductionContext context, DatabaseModel model, TableModel table)
    {
        var sb = new StringBuilder();
        sb.AppendLine($@"// <auto-generated/> // {DatabaseSourceGenerator.GenerationStamp()}

using System;
using IntegrityTables;
using System.Runtime.CompilerServices;
");
        if (!string.IsNullOrEmpty(table.NameSpace))
        {
            sb.AppendLine($"namespace {table.NameSpace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($@"
    // {DatabaseSourceGenerator.GenerationStamp()}
    public class {table.TypeName}RowContainer : IRowContainer
    {{
        internal const byte DELETED = 0b1;
        internal const byte MODIFIED = 0b10;
        internal const byte ADDED = 0b10;

        public int Version => _version;

        internal Stack<int> _freeSlots = new Stack<int>();
        private int _version = 0;
        internal {table.TypeName}Row[] _facades = Array.Empty<{table.TypeName}Row>();
        internal byte[] _flags = Array.Empty<byte>();
        internal int[] _ids = Array.Empty<int>();
{GenerateFields(context, table)}        
        internal int _count;

        {model.TypeName} _database;
 
        // {DatabaseSourceGenerator.GenerationStamp()}
        public {table.TypeName}RowContainer({model.TypeName} database)
        {{
            this._database = database;
            var _initialRowCapacity = 16;
            _count = 0;
            _facades = new {table.TypeName}Row[_initialRowCapacity];
            _flags = new byte[_initialRowCapacity];
            _ids = new int[_initialRowCapacity];
{ConstructFields(context, table)}            
        }}
        
        // {DatabaseSourceGenerator.GenerationStamp()}
        public int Count => _count - _freeSlots.Count;

        public int Capacity => _facades.Length;
        
        // {DatabaseSourceGenerator.GenerationStamp()}
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool ContainsKey(int id) => id >= 0 && id < _flags.Length && !IsEmpty(id);

        // {DatabaseSourceGenerator.GenerationStamp()}
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int Add(in {table.TypeName} row)
        {{
            int slot;
            if(!_freeSlots.TryPop(out slot))
            {{
                if (_count == _flags.Length) Resize(_count * 2);
                slot = _count++;
            }}
            _ids[slot] = slot;
            var facade = _facades[slot] = new {table.TypeName}Row(slot, this, _database);
            try {{
{AssignFacadeFields(context, table)}
            }} catch(InvalidOperationException) {{
                _count--;
                throw;
            }}
            _flags[slot] = ADDED;
            return slot;
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal bool IsEmpty(int index) => _flags[index] == 0b0 || HasFlag(index, DELETED);

        // {DatabaseSourceGenerator.GenerationStamp()}
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal void SetFlag(int index, byte flag) => _flags[index] |= flag;

        // {DatabaseSourceGenerator.GenerationStamp()}
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool HasFlag(int index, byte flag) => (_flags[index] & flag) != 0;

        // {DatabaseSourceGenerator.GenerationStamp()}
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void ClearFlag(int index, int flag) => _flags[index] &= (byte)~(flag);
        
        // {DatabaseSourceGenerator.GenerationStamp()}
        public void ClearAllFlags() => Array.Clear(_flags, 0, _count);

        // {DatabaseSourceGenerator.GenerationStamp()}
        private void Resize(int _initialRowCapacity)
        {{
            if (_initialRowCapacity <= _flags.Length) return;
            Array.Resize(ref _facades, _initialRowCapacity);
            Array.Resize(ref _flags, _initialRowCapacity);
            Array.Resize(ref _ids, _initialRowCapacity);
{ResizeArrays(context, table)}            
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        public ref {table.TypeName}Row Get(int id) 
        {{
            if (id < 0 || id >= _flags.Length)
                throw new KeyNotFoundException($""Row with id {{id}} does not exist in {table.TypeName}RowContainer"");
            if(IsEmpty(id))
                throw new KeyNotFoundException($""Row with id {{id}} does not exist in {table.TypeName}RowContainer"");
            return ref this._facades[id];
        }}

        internal void Remove(int index)
        {{
            if(!HasFlag(index, DELETED))
            {{
                SetFlag(index, DELETED);
                _freeSlots.Push(index);
            }}
            _ids[index] = -1;
            _facades[index] = default;
            ClearFlag(index, ADDED);
{RemoveArrays(context, table)}            
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        public void Clear()
        {{
            Array.Clear(_facades, 0, _count);
            Array.Clear(_ids, 0, _count);
            Array.Clear(_flags, 0, _count);
 {ClearArrays(context, table)}            
        }}

        public Enumerator GetEnumerator() => new Enumerator(this);

        public struct Enumerator {{
            public int Current {{ get; private set; }}
            int index;
            {table.TypeName}RowContainer container;

            public Enumerator({table.TypeName}RowContainer container)
            {{
                this.container = container;
                this.index = -1;
                Current = -1;
            }}

            public bool MoveNext()
            {{
                while (++index < container._count)
                {{
                    if (!container.HasFlag(index, DELETED))
                    {{
                        Current = index;
                        return true;
                    }}
                }}
                return false;
            }}
        }}
    }}

");
        if (!string.IsNullOrEmpty(table.NameSpace)) sb.AppendLine("}");
        context.AddSource($"{model.FileName("RowContainer", table.TypeName)}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
    
    private static string RemoveArrays(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            sb.AppendLine($"            _{field.Name}[index] = default;");
        }
        return sb.ToString();
    }

    private static string ClearArrays(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            sb.AppendLine($"            Array.Clear(_{field.Name}, 0, _{field.Name}.Length);");
        }
        return sb.ToString();
    }

    private static string ResizeArrays(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            sb.AppendLine($"            Array.Resize(ref _{field.Name}, _initialRowCapacity);");
        }
        return sb.ToString();
    }

    private static string AssignFacadeFields(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            sb.AppendLine($"                facade.{field.Name} = row.{field.Name};");
        }
        return sb.ToString();
    }

    private static string GenerateFields(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            sb.AppendLine($"        internal {field.QualifiedTypeName}[] _{field.Name} = Array.Empty<{field.QualifiedTypeName}>();{(field.IsHotField?" //hot field":"")}");
        }
        return sb.ToString();
    }
    
    private static string ConstructFields(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            sb.AppendLine($"            _{field.Name} = new {field.QualifiedTypeName}[_initialRowCapacity];");
        }
        return sb.ToString();
    }
}