using System.Text;
using IntegrityTables.SourceGeneration.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace IntegrityTables.SourceGeneration;

public class RowFacadeSourceGenerator
{
    public static void GenerateCode(SourceProductionContext context, DatabaseModel model, TableModel table)
    {
        var sb = new StringBuilder();
        sb.AppendLine($@"// <auto-generated/> //  {DatabaseSourceGenerator.GenerationStamp()}

using System;
using IntegrityTables;
");
        if (!string.IsNullOrEmpty(table.NameSpace))
        {
            sb.AppendLine($"namespace {table.NameSpace}");
            sb.AppendLine("{");
        }
        var removeChecks = new StringBuilder();
        table.Dependencies.ForEach(dep =>
        {
            removeChecks.AppendLine($"\n            if(database.{dep.TableModel.FacadeName}.IndexOn{dep.CapitalizedName}.ContainsKey(id)) throw new InvalidOperationException($\"Cannot remove {table.TypeName}Row with id {{id}} because it is referenced by {dep.TableModel.FacadeName}.{dep.Name}\");");
        });
        sb.AppendLine($@"
    // {DatabaseSourceGenerator.GenerationStamp()}
    public struct {table.TypeName}Row
    {{
        private int index;
        private {table.TypeName}RowContainer container;
        private {model.TypeName} database;

        public {table.TypeName}Row(int index, {table.TypeName}RowContainer container, {model.TypeName} database)
        {{
            this.index = index;
            this.container = container;
            this.database = database;
        }}

        public void Save() => container.SetFlag(index, {table.TypeName}RowContainer.MODIFIED);

        public void Remove() {{{removeChecks}
            container.Remove(index);
        }}

        private void AddToIndex(IntMap<IntSet> index, int value, int id)
        {{
            if (!index.TryGetValue(value, out var set))
                index[value] = set = new IntSet();
            set.Add(id);
        }}
        
        private void RemoveFromIndex(IntMap<IntSet> index, int value, int id)
        {{
            if (index.TryGetValue(value, out var set))
                set.Remove(id);
        }}

        public int id => container._ids[index];

{GeneratePropertyAccessors(context, table)}        
    }}  

");
        if (!string.IsNullOrEmpty(table.NameSpace)) sb.AppendLine("}");
        context.AddSource($"{model.FileName("Row", table.TypeName)}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
    
    private static string GeneratePropertyAccessors(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            var checkReference = string.Empty;
            if (field.IsReference)
            {
                if (field.IsNotNull)
                {
                    checkReference = $@"                var oldValue = container._{field.Name}[index];
                if(value < 0) throw new InvalidOperationException($""Cannot set {field.Name} to null, it is a non-nullable reference."");
                if(oldValue == value) return;
                if(!database.{field.ReferencedTableModel.FacadeName}.ContainsKey(value)) 
                    throw new InvalidOperationException($""Row with id {{value}} does not exist in {field.ReferencedTableModel.FacadeName}."");
                else 
                {{
                    RemoveFromIndex(database.{table.FacadeName}.IndexOn{field.CapitalizedName}, oldValue, id);
                    AddToIndex(database.{table.FacadeName}.IndexOn{field.CapitalizedName}, value, id);
                }}";
                }
                else
                {
                    checkReference = $@"                var oldValue = container._{field.Name}[index];
                if(oldValue == value) return;
                if(value >= 0) {{
                    if(!database.{field.ReferencedTableModel.FacadeName}.ContainsKey(value)) 
                        throw new InvalidOperationException($""Row with id {{value}} does not exist in {field.ReferencedTableModel.FacadeName}."");
                    else 
                    {{
                        AddToIndex(database.{table.FacadeName}.IndexOn{field.CapitalizedName}, value, id);
                    }}
                }}
                if(oldValue >= 0) RemoveFromIndex(database.{table.FacadeName}.IndexOn{field.CapitalizedName}, oldValue, id);";
                }
            }
            sb.AppendLine(@$"        public {field.QualifiedTypeName} {field.Name}
        {{
            get => container._{field.Name}[index];
            set 
            {{
{checkReference}
                container._{field.Name}[index] = value;
            }}
        }}");
        }
        return sb.ToString();
    }
}