using System.Collections.Generic;
using System.Linq;
using IntegrityTables.SourceGeneration.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace IntegrityTables.SourceGeneration;

public class SystemSourceGenerator
{
    public static void GenerateCode(SourceProductionContext context, DatabaseModel model)
    {
        foreach (var system in model.SystemModels)
        {
            GenerateSystemCode(context, model, system);
        }
    }

    private static void GenerateSystemCode(SourceProductionContext context, DatabaseModel model, SystemModel system)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using IntegrityTables;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(system.NameSpace))
        {
            sb.AppendLine($"namespace {system.NameSpace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($@"    // {DatabaseSourceGenerator.GenerationStamp()}
    public partial class {system.TypeName}
    {{
        // IsRaw: {system.IsRaw}
        // Parameters: {string.Join(", ", system.Parameters.Select(p => $"{p.name}"))}
        // Written Fields: {string.Join(", ", system.WrittenFields.Select(f => $"{f.Item1}.{f.Item2}"))}

        private IntSet entities = new();");
        
        // Generate the parameterless Execute method

        GenerateExecuteMethod(sb, model, system);

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(system.NameSpace))
        {
            sb.AppendLine("}");
        }

        var fileName = $"{system.TypeName}.System.g.cs";
        context.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateExecuteMethod(StringBuilder sb, DatabaseModel model, SystemModel system)
    {
        sb.AppendLine($@"        // {DatabaseSourceGenerator.GenerationStamp()}
        public void Execute() {{
            Prepare();
            if(entities.Count > 500 && AllowThreadedExecution) 
                ExecuteThreaded();
            else 
                ExecuteScalar();
        }} 

        // {DatabaseSourceGenerator.GenerationStamp()}
        public void Prepare()
        {{
            entities.Clear();");
        

        // Find the primary table to iterate over (first writable parameter, or first readable if no writable)
        if (system.Parameters.Count == 0)
        {
            sb.AppendLine("            return; // No parameters to process.");
            sb.AppendLine("        }");
            return;
        }
        var firstParam = system.Parameters[0];
        sb.AppendLine($"            entities.UnionWith(database.{firstParam.tableModel.FacadeName}.IndexOnEntityId.Keys);");
        foreach (var param in system.Parameters.Skip(1))
        {
            sb.AppendLine($"            entities.IntersectWith(database.{param.tableModel.FacadeName}.IndexOnEntityId.Keys);");
        }

        sb.AppendLine("            entities.Remove(-1);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine(@"        public void ExecuteScalar()
        {");
        // Generate the method call
        sb.AppendLine(@$"            foreach(var entityId in entities) {{");
        
        var args = new List<string>();
                
        foreach (var param in system.Parameters)
        {
            {
                sb.AppendLine($"                var {param.name} = database.{param.tableModel.FacadeName}.GetByEntityId(entityId);");
                args.Add($"{param.name}");
            }           
        }
        sb.AppendLine(@$"                Execute({string.Join(", ", args)});");
        
        sb.AppendLine(@$"            }}");
        sb.AppendLine(@$"        }}");
        sb.AppendLine();
        sb.AppendLine(@"        public void ExecuteThreaded()
        {
            var pages = ObjectPool<List<IntSet.BitEnumerator>>.Get();
            pages.Clear();
            foreach(var page in entities.Pages()) pages.Add(page);
            Threaded.ForEach(0, pages.Count, (int start, int end) => {
                for (int i = start; i < end; i++)
                {
                    var page = pages[i];
                    foreach (var entityId in page)
                    {");
        foreach (var param in system.Parameters)
        {
            {
                sb.AppendLine($"                        var {param.name} = database.{param.tableModel.FacadeName}.GetByEntityId(entityId);");
            }           
        }
        sb.AppendLine(@$"                       Execute({string.Join(", ", args)});
                    }}
                }}
            }});
            pages.Clear();
            ObjectPool<List<IntSet.BitEnumerator>>.Return(pages);
        }}
        ");
    }
}