using System.Text;
using IntegrityTables.SourceGeneration.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace IntegrityTables.SourceGeneration;

public class TableSourceGenerator
{
    public static void GenerateCode(SourceProductionContext context, DatabaseModel model, TableModel table)
    {
        var sb = new StringBuilder();
        sb.AppendLine($@"// <auto-generated/> // {DatabaseSourceGenerator.GenerationStamp()}

using System;
using IntegrityTables;
using System.Runtime.CompilerServices;
");
        if (!string.IsNullOrEmpty(table.NameSpace))
        {
            sb.AppendLine($"namespace {table.NameSpace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($@"

    public partial class {table.TypeName}Table : Table<{table.TypeName}>
    {{
        {model.TypeName} database;
        
        public {table.TypeName}Table({model.TypeName} database)
        {{
            this.database = database;
            _rowContainer = new {table.TypeName}RowContainer(this.database);
        }}

{GenerateIndexFields(context, table)}
        private readonly {table.TypeName}RowContainer _rowContainer;

        public int Count => _rowContainer.Count;

        public int Capacity => _rowContainer.Capacity;
    
{GenerateAddMethod(context, table)}     

        public void Remove(int id) => _rowContainer.Get(id).Remove();

        public void Clear()
        {{
            foreach (var id in _rowContainer)
            {{
                Remove(id);
            }}
{ClearIndexes(table)}
        }}

        public ref {table.TypeName}Row Get(int id) 
        {{
            return ref _rowContainer.Get(id);
        }}


        public bool ContainsKey(int id) => _rowContainer.ContainsKey(id);

        public {table.TypeName}Row this[int id] => _rowContainer.Get(id);

{GenerateIndexIterators(context, table)}

        public {table.TypeName}RowContainer.Enumerator GetEnumerator() => _rowContainer.GetEnumerator();
        
        public Enumerator Rows => new Enumerator(_rowContainer);

        public struct Enumerator {{
            public ref {table.TypeName}Row Current => ref container.Get(index);
            int index;
            {table.TypeName}RowContainer container;

            public Enumerator GetEnumerator() => this;

            public Enumerator({table.TypeName}RowContainer container)
            {{
                this.container = container;
                this.index = -1;
            }}

            public bool MoveNext()
            {{
                while (++index < container._count)
                {{
                    if (!container.HasFlag(index, {table.TypeName}RowContainer.DELETED))
                    {{
                        return true;
                    }}
                }}
                return false;
            }}
        }}

        public struct IndexEnumerator {{
            public ref {table.TypeName}Row Current => ref container.Get(index);
            int index;
            {table.TypeName}RowContainer container;
            IntSet ids;
            IntSet.Enumerator idsEnumerator;

            public IndexEnumerator GetEnumerator() => this;

            public IndexEnumerator({table.TypeName}RowContainer container, IntSet ids)
            {{
                this.container = container;
                this.ids = ids;
                this.idsEnumerator = ids.GetEnumerator();
                this.index = -1;
            }}

            public bool MoveNext()
            {{
                while (idsEnumerator.MoveNext())
                {{
                    index = idsEnumerator.Current;
                    return true;
                }}
                return false;
            }}

        }}

    }}

");
        if (!string.IsNullOrEmpty(table.NameSpace)) sb.AppendLine("}");
        context.AddSource($"{model.FileName("Table", table.TypeName)}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GenerateAddMethod(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        sb.AppendLine($@"        public int Add({table.TypeName} row)
        {{");
        foreach(var triggerModel in table.Triggers)
        {
            if (triggerModel.MethodName == "BeforeAdd")
            {
                sb.AppendLine($"            {triggerModel.Method.ContainingType.Name}.{triggerModel.MethodName}(database, row);");
            }
        }
        sb.AppendLine(@$"            var id = _rowContainer.Add(in row);");
        foreach(var triggerModel in table.Triggers)
        {
            if (triggerModel.MethodName == "AfterAdd")
            {
                sb.AppendLine($"            {triggerModel.Method.ContainingType.Name}.{triggerModel.MethodName}(database, Get(id));");
            }
        }

        sb.AppendLine("            return id;");
        sb.AppendLine("        }");
            
        return sb.ToString();
    }
    

    private static string GenerateIndexIterators(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            if (!field.IsReference) continue;
            sb.AppendLine($"        public IndexEnumerator SelectBy{field.CapitalizedName}(int value) => new IndexEnumerator(_rowContainer, _indexOn{field.CapitalizedName}[value]);");
        }
        return sb.ToString();
    }

    private static string ClearIndexes(TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            if (field.IsReference)
            {
                sb.AppendLine($"            _indexOn{field.CapitalizedName}.Clear();");
            }
        }
        return sb.ToString();
    }

    private static string GenerateIndexFields(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            if (field.IsReference)
            {
                sb.AppendLine($@"        internal readonly IntMap<IntSet> _indexOn{field.CapitalizedName} = new();
        public IReadOnlyIntMap<IntSet> IndexOn{field.CapitalizedName} => _indexOn{field.CapitalizedName};");
            }
        }
        return sb.ToString();
    }
}