using System.Collections.Generic;
using System.Text;
using IntegrityTables.SourceGeneration.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace IntegrityTables.SourceGeneration;

public class TableSourceGenerator
{
    public static void GenerateCode(SourceProductionContext context, DatabaseModel model, TableModel table)
    {
        var sb = new StringBuilder();
        sb.AppendLine($@"// <auto-generated/> // {DatabaseSourceGenerator.GenerationStamp()}

using System;
using IntegrityTables;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
");
        if (!string.IsNullOrEmpty(table.NameSpace))
        {
            sb.AppendLine($"namespace {table.NameSpace}");
            sb.AppendLine("{");
        }
        var constructorParams = new List<string>();
        foreach (var field in table.Fields)
        {
            constructorParams.Add($"{field.QualifiedTypeName} {field.Name} = default");
        }
        var addParams = string.Join(", ", constructorParams);

        sb.AppendLine($@"
    // {DatabaseSourceGenerator.GenerationStamp()}
    public partial class {table.TypeName}Table : Table<{table.TypeName}>
    {{
        {model.TypeName} database;

        // {DatabaseSourceGenerator.GenerationStamp()}
        public {table.TypeName}Table({model.TypeName} database)
        {{
            this.database = database;
            _rowContainer = new {table.TypeName}RowContainer(this.database);
        }}

{GenerateIndexFields(context, table)}
{GenerateUniqueIndexFields(context, table)}
        private readonly {table.TypeName}RowContainer _rowContainer;

        public int Count => _rowContainer.Count;

        public int Capacity => _rowContainer.Capacity;
    
{GenerateAddMethod(context, table)}     

        public void Remove(int id) => _rowContainer.Get(id).Remove();

        // {DatabaseSourceGenerator.GenerationStamp()}
        public void Clear()
        {{
            foreach (var id in _rowContainer)
            {{
                Remove(id);
            }}
{ClearIndexes(table)}
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        public ref {table.RowTypeName} Get(int id) 
        {{
            return ref _rowContainer.Get(id);
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        public bool ContainsKey(int id) => _rowContainer.ContainsKey(id);

        // {DatabaseSourceGenerator.GenerationStamp()}
        public {table.RowTypeName} this[int id] => _rowContainer.Get(id);

        // {DatabaseSourceGenerator.GenerationStamp()}
        public Span<int> GetIdSpan() => new Span<int>(_rowContainer._ids, 0, _rowContainer._count);

        // {DatabaseSourceGenerator.GenerationStamp()}
        public {table.TypeName}RowContainer.Enumerator GetEnumerator() => _rowContainer.GetEnumerator();
        
        // {DatabaseSourceGenerator.GenerationStamp()}
        public Enumerator Rows => new Enumerator(_rowContainer);

        // {DatabaseSourceGenerator.GenerationStamp()}
        public struct Enumerator {{
            public ref {table.RowTypeName} Current => ref container.Get(index);
            int index;
            {table.TypeName}RowContainer container;

            public Enumerator GetEnumerator() => this;

            public Enumerator({table.TypeName}RowContainer container)
            {{
                this.container = container;
                this.index = -1;
            }}

            public bool MoveNext()
            {{
                while (++index < container._count)
                {{
                    if (!container.HasFlag(index, {table.TypeName}RowContainer.DELETED))
                    {{
                        return true;
                    }}
                }}
                return false;
            }}
        }}

        // {DatabaseSourceGenerator.GenerationStamp()}
        public struct IndexEnumerator {{
            public ref {table.RowTypeName} Current => ref container.Get(index);
            int index;
            {table.TypeName}RowContainer container;
            IntSet ids;
            IntSet.Enumerator idsEnumerator;

            public IndexEnumerator GetEnumerator() => this;

            public IndexEnumerator({table.TypeName}RowContainer container, IntSet ids)
            {{
                this.container = container;
                this.ids = ids;
                this.idsEnumerator = ids.GetEnumerator();
                this.index = -1;
            }}

            public bool MoveNext()
            {{
                while (idsEnumerator.MoveNext())
                {{
                    index = idsEnumerator.Current;
                    return true;
                }}
                return false;
            }}

        }}

    }}

");
        if (!string.IsNullOrEmpty(table.NameSpace)) sb.AppendLine("}");
        context.AddSource($"{model.FileName("Table", table.TypeName)}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GenerateAddMethod(SourceProductionContext context, TableModel table)
    {
        var constructorParams = new List<string>();
        var constructorArgs = new List<string>();

        foreach (var field in table.Fields)
        {
            if(field.IsReference)
                constructorParams.Add($"{field.QualifiedTypeName} {field.Name} = -1");
            else
                constructorParams.Add($"{field.QualifiedTypeName} {field.Name} = default");
            constructorArgs.Add($"{field.Name}");
        }
        var addParams = string.Join(", ", constructorParams);
        var addArgs = string.Join(", ", constructorArgs);
        var sb = new StringBuilder();
        sb.AppendLine($@"        public int Add({addParams})
        {{");
        foreach(var triggerModel in table.Triggers)
        {
            if (triggerModel.MethodName == "BeforeAdd")
            {
                sb.AppendLine($"            {triggerModel.Method.ContainingType.Name}.{triggerModel.MethodName}(database, {addArgs});");
            }
        }
        sb.AppendLine(@$"            var id = _rowContainer.Add({addArgs});");
        foreach(var triggerModel in table.Triggers)
        {
            if (triggerModel.MethodName == "AfterAdd")
            {
                sb.AppendLine($"            {triggerModel.Method.ContainingType.Name}.{triggerModel.MethodName}(database, Get(id));");
            }
        }

        sb.AppendLine("            return id;");
        sb.AppendLine("        }");
            
        return sb.ToString();
    }
    

    private static string ClearIndexes(TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            if (field.IsReference)
            {
                sb.AppendLine($"            _indexOn{field.CapitalizedName}.Clear();");
            }
        }
        return sb.ToString();
    }

    private static string GenerateIndexFields(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            if (field.IsReference)
            {
                if(field.IsUnique)
                {
                    sb.AppendLine($@"        internal readonly IntMap<int> _indexOn{field.CapitalizedName} = new();
        public IntMap<int> IndexOn{field.CapitalizedName} => _indexOn{field.CapitalizedName};
        public {table.RowTypeName} GetBy{field.CapitalizedName}(int value) => Get(_indexOn{field.CapitalizedName}[value]);
        public Span<int> Get{field.CapitalizedName}Span() => new Span<{field.QualifiedTypeName}>(_rowContainer._{field.Name}, 0, _rowContainer._count);");
                }
                else
                {
                    sb.AppendLine($@"        internal readonly IntMap<IntSet> _indexOn{field.CapitalizedName} = new();
        public IntMap<IntSet> IndexOn{field.CapitalizedName} => _indexOn{field.CapitalizedName};
        public IndexEnumerator SelectBy{field.CapitalizedName}(int value) => new IndexEnumerator(_rowContainer, _indexOn{field.CapitalizedName}[value]);
        public Span<int> Get{field.CapitalizedName}Span() => new Span<{field.QualifiedTypeName}>(_rowContainer._{field.Name}, 0, _rowContainer._count);");
                }
            }
        }
        return sb.ToString();
    }
    
    private static string GenerateUniqueIndexFields(SourceProductionContext context, TableModel table)
    {
        var sb = new StringBuilder();
        foreach (var field in table.Fields)
        {
            if (field.IsUnique)
            {
                sb.AppendLine($@"        // {DatabaseSourceGenerator.GenerationStamp()}
        internal readonly UniqueIndex<{field.QualifiedTypeName}> _uniqueIndexOn{field.CapitalizedName} = new();
        
        // {DatabaseSourceGenerator.GenerationStamp()}
        public bool TryGetBy{field.CapitalizedName} ({field.QualifiedTypeName} value, out {table.RowTypeName} row)
        {{
            if(_uniqueIndexOn{field.CapitalizedName}.TryGetValue(value, out var id))
            {{
                row = _rowContainer.Get(id);
                return true;
            }}
            row = default;
            return false;
        }}");
            }
        }
        return sb.ToString();
    }
}