using System;
using System.Collections.Generic;

namespace IntegrityTables;

public partial class Table<T>
{
    // This property contains metadata about the table, it is populated by the source generator.
    public ITableMetadata? Metadata { get; set; }

    // These two actions are used to validate data before adding or updating rows.
    // They can be set to null if no validation is needed. The source generator will generate code 
    // for these actions to ensure referential integrity.
    public Action<T>? ValidateForAdd { get; set; }
    public Action<T, T>? ValidateForUpdate { get; set; }
    
    // This action is used to execute cascading remove operations and maintain referential integrity
    // when a row is removed. The code for this action will be generated by the source generator.
    public Action<int, CascadeOperation>? ExecuteCascadingRemove { get; set; }
    
}
