using System;
using System.Collections.Generic;

namespace IntegrityTables;

public partial class Table<T>
{
    // This property contains metadata about the table, it is populated by the source generator.
    public ITableMetadata? Metadata { get; set; }

    // This action is used to execute cascading remove operations and maintain referential integrity
    // when a row is removed. The code for this action will be generated by the source generator.
    public Action<int, CascadeOperation>? ExecuteCascadingRemove { get; set; }
    
}
